version: "3"
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    volumes:
      - ./build/mysql/mysqld_charset.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3309:3309"
    expose:
      - 3309
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_TCP_PORT: 3309
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      retries: 20
      interval: 5s
      start_period: 30s

  api:   # Service名
    container_name: api   # Dockerコンテナ名 
    build:
      context: .
      dockerfile: ./docker/api/dockerfile
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
    - type: bind   # マウントタイプ
      source: ./omron-sensor-api   # マウント元
      target: /app   # マウントされるコンテナのパス
    - /app/node_modules # node_modulesをマウントしない
    tty: true   # コンテナを起動させ続ける。
    command: sh -c "yarn install && yarn run dev"   # コンテナ起動時に実行するコマンド
    restart: always   # コンテナが停止した場合、自動で再起動する
    depends_on:
      mysql:
        condition: service_healthy

