version: "3"
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    volumes:
      - ./build/mysql/mysqld_charset.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3309:3309"
    expose:
      - 3309
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_TCP_PORT: 3309

  app:   # Service名
    image: node:latest  # Dockerイメージを指定します。
    container_name: api   # Dockerコンテナ名 
    working_dir: /app  # 作業ディレクトリの指定
    ports:
      - "3000:3000"
    volumes:
    - type: bind   # マウントタイプ
      source: ./omron-sensor-api   # マウント元
      target: /app   # マウントされるコンテナのパス
    - /app/node_modules # node_modulesをマウントしない
    tty: true   # コンテナを起動させ続ける。
    command: sh -c "yarn install && yarn run dev"   # コンテナ起動時に実行するコマンド

