version: "3"
services:
  mysql:
    container_name: ${container_name}
    image: mysql:latest
    volumes:
      - ./build/mysql/mysqld_charset.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3309:3309"
    expose:
      - 3309
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_TCP_PORT: 3309

  app:   # Service名
    image: node:latest  # Dockerイメージを指定します。
    container_name: api   # Dockerコンテナ名 
    working_dir: /usr/src/app  # 作業ディレクトリの指定
    volumes:
    - type: bind   # マウントタイプ
      source: ./app   # マウント先
      target: /usr/src/app   # マウントされるコンテナのパス
    tty: true   # コンテナを起動させ続ける。